[package]
name = "goose-eggs"
version = "0.1.1"
authors = ["Jeremy Andrews <jeremy@tag1.com>"]
edition = "2018"
description = "Useful functions for writing Goose load tests."
homepage = "https://goose.rs/"
documentation = "https://docs.rs/goose-snippets/"
repository = "https://github.com/tag1consulting/goose-snippets"
readme = "README.md"
keywords = ["loadtesting", "performance", "web"]
license = "Apache-2.0"

[dependencies]
goose = "0.12"
regex = "1.5"
